// Generated by Selenium IDE
using DOLE.HRIS.NUnit.Test;
using DOLE.HRIS.NUnit.Test.Utilities;
using NUnit.Framework;
using NUnit.Framework.Interfaces;
using OpenQA.Selenium;
using OpenQA.Selenium.Edge;
using OpenQA.Selenium.Interactions;
using OpenQA.Selenium.Support.UI;
using SeleniumExtras.WaitHelpers;
using Serilog;
using Serilog.Core;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.NetworkInformation;
using System.Threading;
using System.Threading.Tasks;

namespace DOLE.HRIS.Application.Automation.Selenium
{
    [TestFixture]
    [Category("Propositos")]
    public class TC001FiltrosTiposFormacionTest
    {
        private readonly string urlEntorno = Environment.GetEnvironmentVariable("UrlApplicationForTesting", EnvironmentVariableTarget.Process);
        private string urlTest = "";
        private readonly string urlScreen = "/Training/Maintenances/TypeTraining.aspx";

        private readonly SeleniumEntity seleniumEntities = new SeleniumEntity("TFF001", "TFF001_TipoFormacionAFiltrar");

        private IWebDriver driver;
        WebDriverWait wait;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        Commons myCommons;

        [SetUp]
        public void SetUp()
        {
            urlTest = !string.IsNullOrEmpty(urlEntorno) ? urlEntorno : ConfigurationManager.AppSettings.Get("UrlApplicationForTesting");
            driver = new EdgeDriver();
            driver.Manage().Window.Maximize();
            myCommons = new Commons();
            myCommons.log();
            wait = new WebDriverWait(driver, TimeSpan.FromSeconds(80));

            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }

        [TearDown]
        protected void TearDown()
        {
            if (TestContext.CurrentContext.Result.Outcome.Status == TestStatus.Failed)
            {
                myCommons.TakeScreenshot(driver, TestContext.CurrentContext.Test.Name);
            }

            driver.Quit();
        }

        [Test]
        public async Task TC001FiltrosTiposFormacion()
        {
            await myCommons.SeleniumSetup(wait, driver, urlTest, urlScreen);
            Thread.Sleep(1000);
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_btnAdd")));

            wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("ctl00_cntBody_btnAdd"))).Click();
            myCommons.Log.Information($"{DateTime.Now}: Esperando que el botón de Aceptar se muestre.");

            // Realiza acciones con el elemento <body>
            {
                var bodyElement = wait.Until(ExpectedConditions.ElementIsVisible(By.TagName("body")));
                Actions builder = new Actions(driver);
                builder.MoveToElement(bodyElement, 0, 0).Perform();
            }


            myCommons.Log.Information($"{DateTime.Now}: Ingresando a la modal de Creación de Tipo Fromación.");

            Thread.Sleep(1000);
            myCommons.TypeTrainingCharacters(wait, driver, js, new List<SeleniumEntity> { seleniumEntities });
            myCommons.Log.Information($"{DateTime.Now}: Se crea el registro con los datos" + seleniumEntities.Code + seleniumEntities.Description);

            myCommons.SearchTrainingTypeByCode(wait, driver, js, seleniumEntities.Code);
            myCommons.Log.Information($"{DateTime.Now}: Buscar el registro recién creado" + seleniumEntities.Code + seleniumEntities.Description);
            Thread.Sleep(1000);

            // Espera para ver si se actualiza
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvTypeTrainingCode")));
            string displayedCode = driver.FindElement(By.Id("dvTypeTrainingCode")).Text;
            myCommons.Log.Information($"Código del tipo de formación recuperado después de la búsqueda: " + seleniumEntities.Code);


            myCommons.Log.Information($"{DateTime.Now}: Se inicia la validación de los assert luego de filtar por ctl00_cntBody_TypeTrainingCodeFilter.");
            Assert.AreEqual(seleniumEntities.Code, displayedCode, "La código del tipo de formación no coincide.");
            myCommons.Log.Information($"{DateTime.Now}: Validando el Assert por dvTypeTrainingCode coincida con {seleniumEntities.Code}.");

            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvTypeTrainingName")));
            string displayedDescription = driver.FindElement(By.Id("dvTypeTrainingName")).Text;
            Assert.AreEqual(seleniumEntities.Description, displayedDescription, "La descripción del propósito no coincide." + seleniumEntities.Description);
            myCommons.Log.Information($"{DateTime.Now}: Validando el Assert por dvTypeTrainingName coincida con: " + seleniumEntities.Description);

            myCommons.SearchTrainingTypeByName(wait, driver, js, seleniumEntities.Description);
            myCommons.Log.Information($"{DateTime.Now}: Buscar el registro recién creado" + seleniumEntities.Code + seleniumEntities.Description);


            myCommons.Log.Information($"{DateTime.Now}: Digitando valor a buscar en el filtro ctl00_cntBody_TypeTrainingNameFilter.  {seleniumEntities.Description}");

            
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_btnSearch")));
            wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("ctl00_cntBody_btnSearch"))).Click();
            myCommons.Log.Information($"Click en el botón de Buscar");

            //Espera que el elemento en el grid sea visble
            Thread.Sleep(1000);

            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvTypeTrainingName")));
            displayedDescription = driver.FindElement(By.Id("dvTypeTrainingName")).Text;
            Assert.AreEqual(seleniumEntities.Description, displayedDescription, "La descripción del tipo de formación no coincide." + seleniumEntities.Description);
            myCommons.Log.Information($"{DateTime.Now}: Validando el Assert por dvTypeTrainingName coincida con:"+ seleniumEntities.Description);
        }
    }
}