// Generated by Selenium IDE
using DOLE.HRIS.NUnit.Test;
using DOLE.HRIS.NUnit.Test.Utilities;
using Microsoft.Win32;
using NUnit.Framework;
using NUnit.Framework.Interfaces;
using OpenQA.Selenium;
using OpenQA.Selenium.Edge;
using OpenQA.Selenium.Interactions;
using OpenQA.Selenium.Support.UI;
using SeleniumExtras.WaitHelpers;
using Serilog;
using Serilog.Core;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.NetworkInformation;
using System.Threading;
using System.Threading.Tasks;
namespace DOLE.HRIS.Application.Automation.Selenium
{
    [TestFixture]
    [Category("Matriz")]
    public class TC002ActivarRegistroBorradoMatrizAlcanceTest
    {
        private readonly string urlEntorno = Environment.GetEnvironmentVariable("UrlApplicationForTesting", EnvironmentVariableTarget.Process);
        private string urlTest = "";
        private readonly string urlScreen = "/Training/Maintenances/MatrixTarget.aspx";

        private readonly SeleniumEntity seleniumEntities = new SeleniumEntity("MAAC001", "MAAC001_MatrizActivar");
        private IWebDriver driver;
        WebDriverWait wait;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;

        string expectedErrorMessage = "Los datos ingresados provocan un conflicto con otro registro por duplicidad de Código.\nLos datos del registro existente son los siguientes:";
        Commons myCommons;

        [SetUp]
        public void SetUp()
        {
            urlTest = !string.IsNullOrEmpty(urlEntorno) ? urlEntorno : ConfigurationManager.AppSettings.Get("UrlApplicationForTesting");
            driver = new EdgeDriver();
            driver.Manage().Window.Maximize();
            myCommons = new Commons();
            myCommons.log();
            wait = new WebDriverWait(driver, TimeSpan.FromSeconds(60));

            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }

        [TearDown]
        protected void TearDown()
        {
            if (TestContext.CurrentContext.Result.Outcome.Status == TestStatus.Failed)
            {
                myCommons.TakeScreenshot(driver, TestContext.CurrentContext.Test.Name);
            }

            driver.Quit();
        }

        [Test]
        public async Task TC002ActivarRegistroBorradoMatrizAlcance()
        {
            await myCommons.SeleniumSetup(wait, driver, urlTest, urlScreen);
            Thread.Sleep(1000);
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_btnAdd")));

            wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("ctl00_cntBody_btnAdd"))).Click();
            myCommons.Log.Information($"{DateTime.Now}: Ingresando a la modal de Creación de Matriz.");

            //AgregarCentro(seleniumEntities);
            Thread.Sleep(500);
            myCommons.Log.Information($"{DateTime.Now}: Ingresando a la modal de Creación de Matriz.");
            myCommons.MatrixTargetCharacters(wait, driver, js, new List<SeleniumEntity> { seleniumEntities });

            myCommons.MatrixTargetByCode(wait, driver, js, seleniumEntities.Code);
            myCommons.Log.Information($"{DateTime.Now}: Buscar el registro." + seleniumEntities.Code);
            Thread.Sleep(1000);
            myCommons.DeleteMatrixTarget(wait, driver, js, seleniumEntities.Code);
            myCommons.Log.Information($"{DateTime.Now}:Se elimina el registro." + seleniumEntities.Code);
            Utilities.CleanFields(js, "ctl00_cntBody_MatrixTargetCodeFilter");
            myCommons.Log.Information($"{DateTime.Now}:limpiar el filtro de Código." + seleniumEntities.Code);

            Thread.Sleep(1000);
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_btnAdd")));
            wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("ctl00_cntBody_btnAdd"))).Click();
            myCommons.Log.Information($"{DateTime.Now}: Ingresando nuevamente en la modal de Creación del Tipo de Formación.");

            Thread.Sleep(1000);
            myCommons.MatrixTargetCharacters(wait, driver, js, new List<SeleniumEntity> { seleniumEntities });

            Thread.Sleep(1000);
            Utilities.CleanFields(js, "ctl00_cntBody_MatrixTargetCodeFilter");
            myCommons.Log.Information($"{DateTime.Now}: Limpiar filtro de código");


            myCommons.MatrixTargetByCode(wait, driver, js, seleniumEntities.Code);
            myCommons.Log.Information($"{DateTime.Now}: Buscar registro recién editado" + seleniumEntities.Code);
            Thread.Sleep(1000);
            wait.Until(ExpectedConditions.ElementExists(By.Id("dvMatrixTargetCode")));
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvMatrixTargetCode")));
            // Los asserts validan que el test case, realmente inserto las aulas
            string displayedCode = driver.FindElement(By.Id("dvMatrixTargetCode")).Text;
            Assert.AreEqual(seleniumEntities.Code, displayedCode, "La código del proposito no coincide.");
            myCommons.Log.Information($"{DateTime.Now}: Validando el Assert por Código de la Matriz  " + seleniumEntities.Code);


            string displayedDescription = driver.FindElement(By.Id("dvMatrixTargetName")).Text;
            Assert.AreEqual(seleniumEntities.Description, displayedDescription, "La descripción de la Matriz no coincide.");
            myCommons.Log.Information($"{DateTime.Now}: Validando el Assert por Descripción del propósito  " + seleniumEntities.Description);
        }
    }
}