// Generated by Selenium IDE
using DOLE.HRIS.NUnit.Test;
using DOLE.HRIS.NUnit.Test.Utilities;
using NUnit.Framework;
using NUnit.Framework.Interfaces;
using OpenQA.Selenium;
using OpenQA.Selenium.Edge;
using OpenQA.Selenium.Interactions;
using OpenQA.Selenium.Support.UI;
using SeleniumExtras.WaitHelpers;
using Serilog;
using Serilog.Core;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace DOLE.HRIS.Application.Automation.Selenium
{
    [TestFixture]
    [Category("AreaTematicas")]
    public class TC003EdicionCaracteresEspecialesAreaTematicaTest
    {
        private readonly string urlEntorno = Environment.GetEnvironmentVariable("UrlApplicationForTesting", EnvironmentVariableTarget.Process);
        private string urlTest = "";
        private readonly SeleniumEntity seleniumEntitiesEdited = new SeleniumEntity("ATC001", @"""ATCscripttest@__:script:LPPñ09987:ÑP@_:@::.@$?*%#$%^*()$$++{}*{[*?>><<!#$%^&*((");

        private readonly List<SeleniumEntity> seleniumEntities = new List<SeleniumEntity>();
        private readonly string urlScreen = "/Training/Maintenances/ThematicAreas.aspx";


        private IWebDriver driver;
        WebDriverWait wait;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        Commons myCommons;

        [SetUp]
        public void SetUp()
        {
            urlTest = !string.IsNullOrEmpty(urlEntorno) ? urlEntorno : ConfigurationManager.AppSettings.Get("UrlApplicationForTesting");
            driver = new EdgeDriver();
            driver.Manage().Window.Maximize();
            myCommons = new Commons();
            myCommons.log();
            wait = new WebDriverWait(driver, TimeSpan.FromSeconds(60));

            seleniumEntities.Add(new SeleniumEntity("ATC001", "ATC001_EditarCaracteres"));

            // Inicializa el ejecutor de JavaScript y el diccionario de variables
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }

        [TearDown]
        protected void TearDown()
        {
            if (TestContext.CurrentContext.Result.Outcome.Status == TestStatus.Failed)
            {
                myCommons.TakeScreenshot(driver, TestContext.CurrentContext.Test.Name);
            }

            driver.Quit();
        }

        [Test]
        public async Task TC003EdicionCaracteresEspecialesAreaTematica()
        {
            await myCommons.SeleniumSetup(wait, driver, urlTest, urlScreen);

            Thread.Sleep(1000);

            wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("ctl00_cntBody_btnAdd"))).Click();
            myCommons.Log.Information($"{DateTime.Now}: Ingresando a la modal de Creación de Areas Temáticas.");

            //Los pasos para completar el formulario de creación de un propósito
            myCommons.ThematicAreaCreateCharacters(wait, driver, js, seleniumEntities);
            myCommons.Log.Information($"{DateTime.Now}: Area Temática creado Exitosamente.");

            myCommons.SearchThematicAreaByCode(wait, driver, js, seleniumEntities[0].Code);
            myCommons.Log.Information($"{DateTime.Now}: Buscar el registro recién creado" + seleniumEntities[0].Code + seleniumEntities[0].Description);
            Thread.Sleep(2000);
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvThematicAreaName")));
            wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("dvThematicAreaName"))).Click();
            myCommons.Log.Information($"{DateTime.Now}: Seleccionar el registro en el grid " + seleniumEntities[0].Code);

            Thread.Sleep(1500);
            var ButtonElement = driver.FindElement(By.Id("ctl00_cntBody_btnEdit"));
            IWebElement fieldElement = wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_btnEdit")));
            wait.Until(ExpectedConditions.ElementToBeClickable((ButtonElement))).Click();
            myCommons.Log.Information($"{DateTime.Now}: Ingresando en la modal de Edición");
            Thread.Sleep(500);

            myCommons.EditThematicArea(wait, driver, js, new List<SeleniumEntity> { seleniumEntitiesEdited });
            myCommons.Log.Information($"{DateTime.Now}: Se edito el rgistro con los valores " + seleniumEntitiesEdited.Code + seleniumEntitiesEdited.Description);

            Thread.Sleep(500);
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_txtThematicAreaCodeFilter")));
            Utilities.CleanFields(js, "ctl00_cntBody_txtThematicAreaCodeFilter");
            driver.FindElement(By.Id("ctl00_cntBody_txtThematicAreaCodeFilter")).SendKeys(seleniumEntities[0].Code);

            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_btnSearch")));
            driver.FindElement(By.Id("ctl00_cntBody_btnSearch")).Click();
            myCommons.Log.Information($"{DateTime.Now}: Buscar el Código" + seleniumEntities[0].Code);


            Thread.Sleep(1000);
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvThematicAreaCode")));
            string displayedCode = driver.FindElement(By.Id("dvThematicAreaCode")).Text;
            Assert.AreEqual("ATC001", displayedCode, "El código del Area no coincide.");
            myCommons.Log.Information($"{DateTime.Now}: Validando el Assert en el campo de Código  " + displayedCode);


            string displayedDescription = driver.FindElement(By.Id("dvThematicAreaName")).Text;
            Assert.AreEqual("ATCscripttest@__:script:LPPñ09987:ÑP@_:@::.@", displayedDescription, "La descripción del Area no coincide.");
            myCommons.Log.Information($"{DateTime.Now}: Validando el Assert en el campo de Descripción  " + displayedDescription);
        }
    }
}