// Generated by Selenium IDE
using DOLE.HRIS.NUnit.Test;
using DOLE.HRIS.NUnit.Test.Utilities;
using NUnit.Framework;
using NUnit.Framework.Interfaces;
using OpenQA.Selenium;
using OpenQA.Selenium.DevTools;
using OpenQA.Selenium.Edge;
using OpenQA.Selenium.Interactions;
using OpenQA.Selenium.Support.UI;
using SeleniumExtras.WaitHelpers;
using Serilog;
using Serilog.Core;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace DOLE.HRIS.Application.Automation.Selenium
{
    [TestFixture]
    [Category("AreaTematicas")]
    public class TC002FiltrosCaracteresEspecialesAreaTematicaTest
    {
        private readonly string urlEntorno = Environment.GetEnvironmentVariable("UrlApplicationForTesting", EnvironmentVariableTarget.Process);
        private string urlTest = "";
        private readonly string urlScreen = "/Training/Maintenances/ThematicAreas.aspx";
        private readonly SeleniumEntity seleniumEntities = new SeleniumEntity(@"AREATEscript/>test!@#$%^*()__++{}:<>?<script/>;:,.[L¨P¨P*ñ{09'987:Ñ[*?P>.><<!@#$%^&*((", @"AREATEscript/>test!@#$%^*()__++{}:<>?<script/>;:,.[L¨P¨P*ñ{09'987:Ñ[*?P>.><<!@#$%^&*((");


        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        WebDriverWait wait;
        Commons myCommons;

        [SetUp]
        public void SetUp()
        {

            urlTest = !string.IsNullOrEmpty(urlEntorno) ? urlEntorno : ConfigurationManager.AppSettings.Get("UrlApplicationForTesting");
            // Inicializa el driver de Edge
            driver = new EdgeDriver();
            myCommons = new Commons();
            wait = new WebDriverWait(driver, TimeSpan.FromSeconds(60));

            driver.Manage().Window.Maximize();
            // Inicializa el ejecutor de JavaScript y el diccionario de variables
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
            myCommons.log();
        }

        [TearDown]
        protected void TearDown()
        {
            if (TestContext.CurrentContext.Result.Outcome.Status == TestStatus.Failed)
            {
                myCommons.TakeScreenshot(driver, TestContext.CurrentContext.Test.Name);
            }

            driver.Quit();
        }

        [Test]
        public async Task TC002FiltrosCaracteresEspecialesAreaTematica()
        {
            await myCommons.SeleniumSetup(wait, driver, urlTest, urlScreen);

            // Espera a que el botón con ID que contiene 'btnAdd' sea clickeable y haz clic en él
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_btnAdd")));

            wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("ctl00_cntBody_btnAdd"))).Click();
            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(20);
            myCommons.Log.Information($"{DateTime.Now}: Ingresando a la modal de Creación de Areas Temáticas.");
            myCommons.ThematicAreaCreateCharacters(wait, driver, js, new List<SeleniumEntity> { seleniumEntities });

            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(20);

            myCommons.SearchThematicAreaByCode(wait, driver, js, seleniumEntities.Code);
            Thread.Sleep(2000);  // Espera para ver si se actualiza


            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvThematicAreaCode")));

            string displayedCode = driver.FindElement(By.Id("dvThematicAreaCode")).Text;
            Assert.AreEqual("AREATEscri", displayedCode, "el código del Area no coincide.");
            myCommons.Log.Information($"{DateTime.Now}: Validando el Assert en el campo de Código  " + displayedCode);


            myCommons.SearchThematicAreaByDescription(wait, driver, js, seleniumEntities.Description);
            myCommons.Log.Information($"{DateTime.Now}: Buscando por nombre de Area  " + seleniumEntities.Description);
            Thread.Sleep(2000);

            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvThematicAreaName")));

            string displayedDescription = driver.FindElement(By.Id("dvThematicAreaName")).Text;
            Assert.AreEqual("AREATEscripttest@__:script:.LPPñ09987:ÑP.@", displayedDescription, "La descripción del centro no coincide.");
            myCommons.Log.Information($"{DateTime.Now}: Validando el Assert en el campo de Descripción  " + displayedDescription);
        }
    }
}