// Generated by Selenium IDE
using DOLE.HRIS.NUnit.Test;
using DOLE.HRIS.NUnit.Test.Utilities;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Edge;
using OpenQA.Selenium.Interactions;
using OpenQA.Selenium.Support.UI;
using SeleniumExtras.WaitHelpers;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Threading;

namespace ProgramasPlanesEntrenamientoEliminar
{
    [TestFixture]
    public class TC002ActivarRegistroBorradoProgramasPlanesEntrenamientoTest
    {
        private readonly string urlTest = ConfigurationManager.AppSettings.Get("UrlApplicationForTesting");
        private readonly SeleniumEntity seleniumEntities = new SeleniumEntity("099S1", "TC001_Deleted001");

        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        //Actions actions;

        [SetUp]
        public void SetUp()
        {
            driver = new EdgeDriver();

            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }

        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }

        [Test]
        public void TC002ActivarRegistroBorradoProgramasPlanesEntrenamiento()
        {
            driver.Navigate().GoToUrl(urlTest + "/Default.aspx");
            driver.Manage().Window.Size = new System.Drawing.Size(945, 1020);
            driver.FindElement(By.CssSelector(".filter-option-inner-inner")).Click();
            driver.FindElement(By.CssSelector("li:nth-child(2) .text")).Click();
            {
                var dropdown = driver.FindElement(By.Id("ctl00_cntBody_cboUserDivisions"));
                dropdown.FindElement(By.XPath("//option[. = 'División de Costa Rica']")).Click();
            }

            driver.FindElement(By.Id("ctl00_cntBody_btnSelectWorkingDivision")).Click();
            driver.Navigate().GoToUrl(urlTest + "/Training/Maintenances/SchoolTraining.aspx");

            Thread.Sleep(3000);

            driver.FindElement(By.XPath("//div[2]/div/div/button")).Click();
            {
                var element = driver.FindElement(By.XPath("//button[@id='ctl00_cntBody_btnAdd']"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element).Perform();
            }
            {
                var element = driver.FindElement(By.TagName("body"));
                Actions builder = new Actions(driver);
                builder.MoveToElement(element, 0, 0).Perform();
            }

            driver.FindElement(By.Id("ctl00_cntBody_SchoolTrainingCodeEdit")).Click();
            driver.FindElement(By.Id("ctl00_cntBody_SchoolTrainingCodeEdit")).SendKeys(seleniumEntities.Code);
           
            driver.FindElement(By.Id("ctl00_cntBody_SchoolTrainingNameEdit")).Click();
            driver.FindElement(By.Id("ctl00_cntBody_SchoolTrainingNameEdit")).SendKeys(seleniumEntities.Description);
            
            driver.FindElement(By.CssSelector("#ctl00_cntBody_uppDialogControl .form-horizontal")).Click();
            driver.FindElement(By.CssSelector(".col-sm-8 .active")).Click();
            driver.FindElement(By.Id("ctl00_cntBody_btnAccept")).Click();

            Thread.Sleep(3000);

            driver.FindElement(By.Id("ctl00_cntBody_btnActivateDeletedAccept")).Click();

            Thread.Sleep(3000);

            WebDriverWait wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
            wait.Until(ExpectedConditions.InvisibilityOfElementLocated(By.CssSelector("div[class='alert alert-autocloseable-msg alert-success'")));

            Thread.Sleep(3000);

            Utilities.CleanFields(js, "ctl00_cntBody_SchoolTrainingCodeFilter");
            driver.FindElement(By.Id("ctl00_cntBody_SchoolTrainingCodeFilter")).SendKeys(seleniumEntities.Code);
            
            driver.FindElement(By.Id("ctl00_cntBody_btnSearch")).Click();

            Thread.Sleep(3000);
        }
    }
}