
// Generated by Selenium IDE
using DOLE.HRIS.NUnit.Test;
using DOLE.HRIS.NUnit.Test.Utilities;
using NUnit.Framework;
using NUnit.Framework.Interfaces;
using OpenQA.Selenium;
using OpenQA.Selenium.Edge;
using OpenQA.Selenium.Interactions;
using OpenQA.Selenium.Support.UI;
using SeleniumExtras.WaitHelpers;
using Serilog;
using Serilog.Core;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace DOLE.HRIS.Application.Automation.Selenium
{
    [TestFixture]
    [Category("Propositos")]
    public class TC003EdicionCaracteresEspecialesPropositoEntrenamientoTest
    {

        private readonly string urlEntorno = Environment.GetEnvironmentVariable("UrlApplicationForTesting", EnvironmentVariableTarget.Process);
        private string urlTest = "";
        private readonly SeleniumEntity seleniumEntitiesEdited = new SeleniumEntity("POC001", "POEscripttest@__:script:LPPñ09987:ÑP@__:s@__::.");

        private readonly List<SeleniumEntity> seleniumEntities = new List<SeleniumEntity>();
        private readonly string urlScreen = "/Training/Maintenances/TrainingPurpose.aspx";


        private IWebDriver driver;
        WebDriverWait wait;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        Commons myCommons;

        [SetUp]
        public void SetUp()
        {
            urlTest = !string.IsNullOrEmpty(urlEntorno) ? urlEntorno : ConfigurationManager.AppSettings.Get("UrlApplicationForTesting");
            driver = new EdgeDriver();
            driver.Manage().Window.Maximize();
            myCommons = new Commons();
            myCommons.log();
            wait = new WebDriverWait(driver, TimeSpan.FromSeconds(60));

            seleniumEntities.Add(new SeleniumEntity("POC001", "POC001_EditarCaracteres"));

            // Inicializa el ejecutor de JavaScript y el diccionario de variables
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            if (TestContext.CurrentContext.Result.Outcome.Status == TestStatus.Failed)
            {
                myCommons.TakeScreenshot(driver, TestContext.CurrentContext.Test.Name);
            }

            driver.Quit();
        }

        [Test]
        public async Task TC003EdicionCaracteresEspecialesPropositoEntrenamiento()
        {
            await myCommons.SeleniumSetup(wait, driver, urlTest, urlScreen);

            Thread.Sleep(1000);
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_btnAdd")));
            wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("ctl00_cntBody_btnAdd"))).Click();
            myCommons.Log.Information($"{DateTime.Now}: Ingresando a la modal de Creación de Propósitos.");

            //Los pasos para completar el formulario de creación de un propósito
            myCommons.AgregarProposito(wait, driver, js, seleniumEntities);
            myCommons.Log.Information($"{DateTime.Now}: Propósito creado Exitosamente.");

            myCommons.BuscarPropositoPorCodigo(wait, driver, js, seleniumEntities[0].Code);
            myCommons.Log.Information($"{DateTime.Now}: Buscar el registro recién creado" + seleniumEntities[0].Code + seleniumEntities[0].Description);
            Thread.Sleep(1000);
            wait.Until(ExpectedConditions.ElementExists(By.Id("dvTrainingProgramName")));
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvTrainingProgramName")));
            wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("dvTrainingProgramName"))).Click();
            myCommons.Log.Information($"{DateTime.Now}: Seleccionar el registro en el grid " + seleniumEntities[0].Code);

            Thread.Sleep(1500);
            var ButtonElement = driver.FindElement(By.Id("ctl00_cntBody_btnEdit"));
            IWebElement fieldElement = wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_btnEdit")));
            wait.Until(ExpectedConditions.ElementToBeClickable((ButtonElement))).Click();
            myCommons.Log.Information($"{DateTime.Now}: Ingresando en la modal de Edición");
            Thread.Sleep(1000);

            myCommons.EditPurposes(wait, driver, js, new List<SeleniumEntity> { seleniumEntitiesEdited});
            myCommons.Log.Information($"{DateTime.Now}: Se edito el rgistro con los valores " + seleniumEntitiesEdited.Code + seleniumEntitiesEdited.Description);

        
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_txtTrainingProgramCodeFilter")));
            Utilities.CleanFields(js, "ctl00_cntBody_txtTrainingProgramCodeFilter");
            wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("ctl00_cntBody_txtTrainingProgramCodeFilter"))).Click();
            driver.FindElement(By.Id("ctl00_cntBody_txtTrainingProgramCodeFilter")).SendKeys(seleniumEntities[0].Code);

            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_btnSearch")));
            wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("ctl00_cntBody_btnSearch"))).Click();
            myCommons.Log.Information($"{DateTime.Now}: Buscar el Código" + seleniumEntities[0].Code);


            Thread.Sleep(500);
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvTrainingProgramCode")));
            string displayedCode = driver.FindElement(By.Id("dvTrainingProgramCode")).Text;
            Assert.AreEqual("POC001", displayedCode, "La código del rorpósito no coincide.");
            myCommons.Log.Information($"{DateTime.Now}: Validando el Assert en el campo de Código  " + displayedCode);


            string displayedDescription = driver.FindElement(By.Id("dvTrainingProgramName")).Text;
            Assert.AreEqual("POEscripttest@__:script:LPPñ09987:ÑP@__:s@__::.", displayedDescription, "La descripción del propósito no coincide.");
            myCommons.Log.Information($"{DateTime.Now}: Validando el Assert en el campo de Descripción  " + displayedDescription);
        }

    }
}