// Generated by Selenium IDE
using DOLE.HRIS.NUnit.Test;
using DOLE.HRIS.NUnit.Test.Utilities;
using NUnit.Framework;
using NUnit.Framework.Interfaces;
using OpenQA.Selenium;
using OpenQA.Selenium.Edge;
using OpenQA.Selenium.Interactions;
using OpenQA.Selenium.Support.UI;
using SeleniumExtras.WaitHelpers;
using Serilog;
using Serilog.Core;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Net.NetworkInformation;
using System.Threading;
using System.Threading.Tasks;

namespace DOLE.HRIS.Application.Automation.Selenium
{
    [TestFixture]
    [Category("Aulas")]
    public class TC002ActivarRegistroBorradoCentroEntrenamientoTest
    {
        private readonly string urlEntorno = Environment.GetEnvironmentVariable("UrlApplicationForTesting", EnvironmentVariableTarget.Process);
        private string urlTest = "";
        private readonly string urlScreen = "/Training/Maintenances/TrainingCenters.aspx";

        private readonly SeleniumEntity seleniumEntities = new SeleniumEntity("CAC001", "CAC001_CentroReactivar");
        private IWebDriver driver;
        WebDriverWait wait;

        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        string expectedErrorMessage = "Los datos ingresados provocan un conflicto con otro registro por duplicidad de código.\nLos datos del registro existente son los siguientes:";
        Commons myCommons;

        [SetUp]
        public void SetUp()
        {
            urlTest = !string.IsNullOrEmpty(urlEntorno) ? urlEntorno : ConfigurationManager.AppSettings.Get("UrlApplicationForTesting");
            driver = new EdgeDriver();
            driver.Manage().Window.Maximize();
            myCommons = new Commons();
            myCommons.log();
            wait = new WebDriverWait(driver, TimeSpan.FromSeconds(90));

            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }

        [TearDown]
        protected void TearDown()
        {
            if (TestContext.CurrentContext.Result.Outcome.Status == TestStatus.Failed)
            {
                myCommons.TakeScreenshot(driver, TestContext.CurrentContext.Test.Name);
            }

            driver.Quit();
        }

        [Test]
        public async Task TC002ActivarRegistroBorradoCentroEntrenamiento()
        {
            await myCommons.SeleniumSetup(wait, driver, urlTest, urlScreen);
            Thread.Sleep(2000);
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_btnAdd")));

            wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("ctl00_cntBody_btnAdd"))).Click();
            myCommons.Log.Information($"{DateTime.Now}: Ingresando a la modal de Creación de Centros.");
                 
            //AgregarCentro(seleniumEntities);
            myCommons.AgregarCentro(wait, driver, js, new List<SeleniumEntity> { seleniumEntities });

            myCommons.BuscarCentros(wait, driver, js, seleniumEntities.Code);
            myCommons.Log.Information($"{DateTime.Now}: Buscar el registro." + seleniumEntities.Code);

            myCommons.BorrarCentroCapacitacion(wait, driver, js, seleniumEntities.Code);
            myCommons.Log.Information($"{DateTime.Now}:Se elimina el registro." + seleniumEntities.Code);
            Utilities.CleanFields(js, "ctl00_cntBody_txtTrainingCenterCodeFilter");
            myCommons.Log.Information($"{DateTime.Now}:limpiar el filtro de Código." + seleniumEntities.Code);

           Thread.Sleep(1000);
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_btnAdd")));
            wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("ctl00_cntBody_btnAdd"))).Click();
            myCommons.Log.Information($"{DateTime.Now}: Ingresando nuevamente en la modal de Creación de Centros.");
            

            AgregarCentroActivar();
            //Assert para validar la modal de Registro Desactivado
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_divActivateDeletedDialog")));
            string errorMessage = driver.FindElement(By.Id("ctl00_cntBody_divActivateDeletedDialog")).Text;
            errorMessage = errorMessage.Replace("\r", "");
            Assert.AreEqual(expectedErrorMessage, errorMessage, "El mensaje de error no coincide con el esperado.");
            myCommons.Log.Information($"{DateTime.Now}:Despliegue de modal de Registro desactivado con el mensaje " + expectedErrorMessage);


            driver.FindElement(By.Id("ctl00_cntBody_btnActivateDeletedAccept")).Click();
            myCommons.Log.Information($"{DateTime.Now}: Botón de Aceptar para agregar nuevamente el registro Desactivado") ;

            wait.Until(ExpectedConditions.ElementIsVisible(By.CssSelector("div.alert.alert-autocloseable-msg.alert-success")));
            var alert = driver.FindElements(By.CssSelector("div.alert.alert-autocloseable-msg.alert-success"));
            if (alert.Count > 0)
            {
                wait.Until(ExpectedConditions.ElementIsVisible(By.CssSelector("div.alert.alert-autocloseable-msg.alert-success")));
            }
            else
            {
                myCommons.Log.Information("No se encontró la alerta de éxito");
            }
            wait.Until(ExpectedConditions.InvisibilityOfElementLocated(By.CssSelector("div.alert.alert-autocloseable-msg.alert-success")));

            Thread.Sleep(1500);


            myCommons.BuscarCentros(wait, driver, js, seleniumEntities.Code);

            Thread.Sleep(1000);
            // Los asserts validan que el test case, realmente inserto los centros
           string displayedCode = driver.FindElement(By.Id("dvTrainingCenterCode")).Text;
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvTrainingCenterCode")));

            Assert.AreEqual(seleniumEntities.Code, displayedCode, "La código del centro no coincide.");
            myCommons.Log.Information($"{DateTime.Now}: Validando el Assert por Código del Centro  " + seleniumEntities.Code);

            string displayedDescription = driver.FindElement(By.Id("dvTrainingCenterDescription")).Text;
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvTrainingCenterDescription")));
            Assert.AreEqual(seleniumEntities.Description, displayedDescription, "La descripción del Centro no coincide.");
            myCommons.Log.Information($"{DateTime.Now}: Validando el Assert por Descripción del Centro de capacitación  " + seleniumEntities.Description);

            string displayedPlaceLocation = driver.FindElement(By.Id("dvPlaceLocation")).Text;
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvPlaceLocation")));
            Assert.AreEqual("Interno", displayedPlaceLocation, "El lugar centro de capacitación no coincide.");
            myCommons.Log.Information($"{DateTime.Now}: Validando el Assert para el Lugar del Centro de Capacitación   " + displayedPlaceLocation);


            //Thread.Sleep(3000);
        }

        private void AgregarCentroActivar()
        {

            // driver.FindElement(By.Id("ctl00_cntBody_txtTrainingCenterCode")).SendKeys(seleniumEntities.Code);

            Serilog.Log.Information($"{DateTime.Now}: Ingresando modal de creación de Centros");
            IWebElement fieldElement = wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_txtTrainingCenterCode")));
            driver.FindElement(By.Id("ctl00_cntBody_txtTrainingCenterCode")).Click();
            driver.FindElement(By.Id("ctl00_cntBody_txtTrainingCenterCode")).SendKeys(seleniumEntities.Code);
            Serilog.Log.Information($"{DateTime.Now}: Ingresando el código del Centro " + seleniumEntities.Code);

            driver.FindElement(By.Id("ctl00_cntBody_txtTrainingCenterDescription")).Click();
            driver.FindElement(By.Id("ctl00_cntBody_txtTrainingCenterDescription")).SendKeys(seleniumEntities.Description);
            Serilog.Log.Information($"{DateTime.Now}: Cambiando Lugar" + "Externo");


            wait = new WebDriverWait(driver, TimeSpan.FromSeconds(10));
            var locationDropdown = new SelectElement(wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_cboPlaceLocation"))));
            locationDropdown.SelectByText("Interno");
            Serilog.Log.Information($"{DateTime.Now}: Seleccionando Lugar" + "Interno");

            driver.FindElement(By.CssSelector("#ctl00_cntBody_uppDialogControl .form-horizontal")).Click();
            driver.FindElement(By.CssSelector(".col-sm-8 .active")).Click();
            Serilog.Log.Information($"{DateTime.Now}: Seleccionando la opción de Habilitado con SI");

            driver.FindElement(By.Id("ctl00_cntBody_btnAccept")).Click();
            Serilog.Log.Information($"{DateTime.Now}:Clcik en en boton de Aceptar para guardar el registro");

            Serilog.Log.Information($"{DateTime.Now}: Registro creado.   " + seleniumEntities.Code + seleniumEntities.Description);

        }
    }
}