// Generated by Selenium IDE
using DOLE.HRIS.Application.Automation.Selenium;
using DOLE.HRIS.NUnit.Test;
using NUnit.Framework;
using NUnit.Framework.Interfaces;
using OpenQA.Selenium;
using OpenQA.Selenium.Edge;
using OpenQA.Selenium.Interactions;
using OpenQA.Selenium.Support.UI;
using SeleniumExtras.WaitHelpers;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Threading;
using System.Threading.Tasks;

namespace DOLE.HRIS.Application.Automation.Selenium
{
    [TestFixture]
    [Category("Cursos")]
    public class TC001CreacionCursosClasificacionTest
    {
        private readonly string urlEntorno = Environment.GetEnvironmentVariable("UrlApplicationForTesting", EnvironmentVariableTarget.Process);
        private string urlTest = "";
        private readonly List<SeleniumEntity> seleniumEntities = new List<SeleniumEntity>();
        private readonly string urlScreen = "/Training/Maintenances/ClassificationCourse.aspx";


        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        WebDriverWait wait;
        Commons myCommons;

        [SetUp]
        public void SetUp()
        {
            urlTest = !string.IsNullOrEmpty(urlEntorno) ? urlEntorno : ConfigurationManager.AppSettings.Get("UrlApplicationForTesting");
            // Inicializa el driver de Edge
            driver = new EdgeDriver();
            myCommons = new Commons();
            myCommons.log();

            wait = new WebDriverWait(driver, TimeSpan.FromSeconds(30));
            driver.Manage().Window.Maximize();

            // Inicializa el ejecutor de JavaScript y el diccionario de variables
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();

            seleniumEntities.Add(new SeleniumEntity("CCL001", "CCL001_ClassificationCourseCreate1"));
            seleniumEntities.Add(new SeleniumEntity("CCL002", "CCL002_ClassificationCourseCreate2"));
        }

        [TearDown]
        protected void TearDown()
        {
            if (TestContext.CurrentContext.Result.Outcome.Status == TestStatus.Failed)
            {
                myCommons.TakeScreenshot(driver, TestContext.CurrentContext.Test.Name);
            }

            driver.Quit();
        }

        [Test]
        public async Task TC001CreacionCursosClasificacion()
        {
            await myCommons.SeleniumSetup(wait, driver, urlTest, urlScreen);


            for (int i = 0; i < 2; i++)
            {
                Thread.Sleep(1000);
                // Espera a que el botón con ID que contiene 'btnAdd' sea clickeable y haz clic en él
                wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_btnAdd")));
                wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("ctl00_cntBody_btnAdd"))).Click();
                myCommons.Log.Information($"{DateTime.Now}: Ingresando a la modal de Creación de Cursos de Clasifiación.");

                Thread.Sleep(1500);
                myCommons.ClassificationCourseCreate(wait, driver, js, i, seleniumEntities);


                myCommons.ClassificationCourseByCode(wait, driver, js, seleniumEntities[i].Code);
                
                
                Thread.Sleep(2000);
                wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvClassificationCourseCode")));
                myCommons.Log.Information($"{DateTime.Now}: Buscando el Curso de Clasificación creado  " + seleniumEntities[i].Code);

                // Los asserts validan que el test case, realmente inserto las aulas

                string displayedCode = driver.FindElement(By.Id("dvClassificationCourseCode")).Text;
                Assert.AreEqual(seleniumEntities[i].Code, displayedCode, "El código del Curso Clasificación no coincide.");
                myCommons.Log.Information($"{DateTime.Now}: Validando el Assert por Código del Curso Clasificación  " + seleniumEntities[i].Code);


                string displayedDescription = driver.FindElement(By.Id("dvClassificationCourseDesEs")).Text;
                Assert.AreEqual(seleniumEntities[i].Description, displayedDescription, "La descripción del Curso Clasificación no coincide.");
                myCommons.Log.Information($"{DateTime.Now}: Validando el Assert por Descripción del Curso Clasificación " + seleniumEntities[i].Description);
            }
        }
    }
}