// Generated by Selenium IDE
using DOLE.HRIS.NUnit.Test;
using DOLE.HRIS.NUnit.Test.Utilities;
using NUnit.Framework;
using NUnit.Framework.Interfaces;
using OpenQA.Selenium;
using OpenQA.Selenium.Edge;
using OpenQA.Selenium.Support.UI;
using SeleniumExtras.WaitHelpers;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Threading;
using System.Threading.Tasks;

namespace DOLE.HRIS.Application.Automation.Selenium
{
    [TestFixture]
    [Category("Cursos")]
    public class TC002FiltrosCaracteresEspecialesCursosClasificacionTest
    {
        private readonly string urlEntorno = Environment.GetEnvironmentVariable("UrlApplicationForTesting", EnvironmentVariableTarget.Process);
        private string urlTest = "";
        private readonly string urlScreen = "/Training/Maintenances/ClassificationCourse.aspx";
        private readonly SeleniumEntity seleniumEntities = new SeleniumEntity(@"CURCLAscript/>test!@#$%^*()__++{}:<>?<script/>;:,.[L¨P¨P*ñ{09'987:Ñ[*?P>.><<!@#$%^&*((", @"CURCLAscript/>test!@#$%^*()__++{}:<>?<script/>;:,.[L¨P¨P*ñ{09'987:Ñ[*?P>.><<!@#$%^&*((");


        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        WebDriverWait wait;
        Commons myCommons;


        [SetUp]
        public void SetUp()
        {
            urlTest = !string.IsNullOrEmpty(urlEntorno) ? urlEntorno : ConfigurationManager.AppSettings.Get("UrlApplicationForTesting");
            // Inicializa el driver de Edge
            driver = new EdgeDriver();
            myCommons = new Commons();
            wait = new WebDriverWait(driver, TimeSpan.FromSeconds(60));

            driver.Manage().Window.Maximize();
            // Inicializa el ejecutor de JavaScript y el diccionario de variables
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
            myCommons.log();
        }

        [TearDown]
        protected void TearDown()
        {
            if (TestContext.CurrentContext.Result.Outcome.Status == TestStatus.Failed)
            {
                myCommons.TakeScreenshot(driver, TestContext.CurrentContext.Test.Name);
            }

            driver.Quit();
        }

        [Test]
        public async Task TC002FiltrosCaracteresEspecialesCursosClasificacion()
        {
            await myCommons.SeleniumSetup(wait, driver, urlTest, urlScreen);

            // Espera a que el botón con ID que contiene 'btnAdd' sea clickeable y haz clic en él
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_btnAdd")));

            wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("ctl00_cntBody_btnAdd"))).Click();
            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(20);
            myCommons.Log.Information($"{DateTime.Now}: Ingresando a la modal de Creación de Cursos de Clasificación.");
            myCommons.ClassificationCourseCreateCharacters(wait, driver, js, new List<SeleniumEntity> { seleniumEntities });

            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(20);

            //myCommons.ClassificationCourseByCode(wait, driver, js, seleniumEntities.Code);


            wait.Until(ExpectedConditions.ElementIsVisible((By.Id("ctl00_cntBody_ClassCodeFilter"))));
            wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("ctl00_cntBody_ClassCodeFilter"))).Click();

            Utilities.CleanFields(js, "ctl00_cntBody_ClassCodeFilter");
            Utilities.CleanFields(js, "ctl00_cntBody_ClassDesESFilter");
            wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("ctl00_cntBody_ClassCodeFilter"))).Click();
            driver.FindElement(By.Id("ctl00_cntBody_ClassCodeFilter")).SendKeys("CURCLAscri");

            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_btnSearch")));
            wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("ctl00_cntBody_btnSearch"))).Click();
            Serilog.Log.Information($"{DateTime.Now}: Buscando Curso de Clasificación " + "CURCLAscri");

          
            Thread.Sleep(1000);  // Espera para ver si se actualiza

            wait.Until(ExpectedConditions.ElementExists(By.Id("dvClassificationCourseCode")));
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvClassificationCourseCode")));

            string displayedCode = driver.FindElement(By.Id("dvClassificationCourseCode")).Text;
            Assert.AreEqual("CURCLAscri", displayedCode, "el código del curso de Clasificación no coincide.");
            myCommons.Log.Information($"{DateTime.Now}: Validando el Assert en el campo de Código  " + displayedCode);


            myCommons.ClassificationCourseByDescription(wait, driver, js, seleniumEntities.Description);
            myCommons.Log.Information($"{DateTime.Now}: Buscando por nombre del Cursos de Clasificación  " + seleniumEntities.Description);
            Thread.Sleep(1000);

            wait.Until(ExpectedConditions.ElementExists(By.Id("dvClassificationCourseDesEs")));
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvClassificationCourseDesEs")));

            string displayedDescription = driver.FindElement(By.Id("dvClassificationCourseDesEs")).Text;
            Assert.AreEqual("CURCLAscripttest@__:script:.LPPñ09987:ÑP.@", displayedDescription, "La descripción del Curso de Clasificación no coincide.");
            myCommons.Log.Information($"{DateTime.Now}: Validando el Assert en el campo de Descripción  " + displayedDescription);
        }
    }
}