// Generated by Selenium IDE
using DOLE.HRIS.NUnit.Test;
using DOLE.HRIS.NUnit.Test.Utilities;
using NUnit.Framework;
using NUnit.Framework.Interfaces;
using OpenQA.Selenium;
using OpenQA.Selenium.DevTools;
using OpenQA.Selenium.Edge;
using OpenQA.Selenium.Interactions;
using OpenQA.Selenium.Support.UI;
using SeleniumExtras.WaitHelpers;
using Serilog;
using Serilog.Core;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace DOLE.HRIS.Application.Automation.Selenium
{
    [TestFixture]
    [Category("Escuelas")]
    public class TC001FiltrosEscuelaEntrenamientoTest
    {
        private readonly string urlEntorno = Environment.GetEnvironmentVariable("UrlApplicationForTesting", EnvironmentVariableTarget.Process);
        private readonly SeleniumEntity seleniumEntities = new SeleniumEntity("SHF001", "SHF001_EscuelaAFiltrar");
        private string urlTest = "";
        private readonly string urlScreen = "/Training/Maintenances/SchoolTraining.aspx";


        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        WebDriverWait wait;
        Commons myCommons;

        [SetUp]
        public void SetUp()
        {
            urlTest = !string.IsNullOrEmpty(urlEntorno) ? urlEntorno : ConfigurationManager.AppSettings.Get("UrlApplicationForTesting");
            // Inicializa el driver de Edge
            driver = new EdgeDriver();
            myCommons = new Commons();
            wait = new WebDriverWait(driver, TimeSpan.FromSeconds(60));

            driver.Manage().Window.Maximize();
            // Inicializa el ejecutor de JavaScript y el diccionario de variables
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
            myCommons.log();
        }

        [TearDown]
        protected void TearDown()
        {
            if (TestContext.CurrentContext.Result.Outcome.Status == TestStatus.Failed)
            {
                myCommons.TakeScreenshot(driver, TestContext.CurrentContext.Test.Name);
            }

            driver.Quit();
        }

        [Test]
        public async Task TC001FiltrosEscuelaEntrenamiento()
        {
            await myCommons.SeleniumSetup(wait, driver, urlTest, urlScreen);
            Thread.Sleep(1000);
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("ctl00_cntBody_btnAdd")));

            wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("ctl00_cntBody_btnAdd"))).Click();
            myCommons.Log.Information($"{DateTime.Now}: Esperando que el botón de Aceptar se muestre.");

            // Realiza acciones con el elemento <body>
            {
                var bodyElement = wait.Until(ExpectedConditions.ElementIsVisible(By.TagName("body")));
                Actions builder = new Actions(driver);
                builder.MoveToElement(bodyElement, 0, 0).Perform();
            }

           myCommons.Log.Information($"{DateTime.Now}: Ingresando a la modal de Creación de Centros.");
     
           myCommons.SchoolTrainingCreateCharacters(wait, driver, js, new List<SeleniumEntity> { seleniumEntities });

           myCommons.SearchSchoolByCode(wait, driver, js, seleniumEntities.Code);
           Thread.Sleep(1000);

           wait.Until(ExpectedConditions.ElementExists(By.Id("dvSchoolTrainingCode")));
           wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvSchoolTrainingCode")));
           IWebElement element = wait.Until(ExpectedConditions.ElementToBeClickable(By.Id("dvSchoolTrainingCode")));

            // Espera para ver si se actualiza
            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvSchoolTrainingCode")));
            string displayedCode = driver.FindElement(By.Id("dvSchoolTrainingCode")).Text;
            myCommons.Log.Information($"Código de la Escuela recuperado después de la búsqueda: {seleniumEntities.Code}");


            myCommons.Log.Information($"{DateTime.Now}: Se inicia la validación de los assert luego de filtar por ctl00_cntBody_SchoolTrainingCodeFilter.");
            Assert.AreEqual(seleniumEntities.Code, displayedCode, "El código de la Escuela no coincide.");
            myCommons.Log.Information($"{DateTime.Now}: Validando el Assert por dvSchoolTrainingCode coincida con {seleniumEntities.Code}.");


            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvSchoolTrainingName")));
            string displayedDescription = driver.FindElement(By.Id("dvSchoolTrainingName")).Text;
            Assert.AreEqual(seleniumEntities.Description, displayedDescription, "El Nombre del aula no coincide." + seleniumEntities.Description);
            myCommons.Log.Information($"{DateTime.Now}: Validando el Assert por dvSchoolTrainingName coincida con: {seleniumEntities.Description} ");


            myCommons.SearchSchoolByDescription(wait, driver, js, seleniumEntities.Description);

            //Espera que el elemento en el grid sea visble
            Thread.Sleep(1000);

            wait.Until(ExpectedConditions.ElementIsVisible(By.Id("dvSchoolTrainingName")));
            displayedDescription = driver.FindElement(By.Id("dvSchoolTrainingName")).Text;
            Assert.AreEqual(seleniumEntities.Description, displayedDescription, "el nombre de la Escuela no coincide." + seleniumEntities.Description);
            myCommons.Log.Information($"{DateTime.Now}: Validando el Assert por dvSchoolTrainingName coincida con: {seleniumEntities.Description} ");


            

        }
    }
}